insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Plug Power, Inc.', 'Peschmann', 'Yovonnda', 'Nuttall', '22/05/1909');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Fidelity Southern Corporation', 'Gapper', 'Hieronymus', 'Worswick', '03/07/1988');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Global X Longevity Thematic ETF', 'Leyborne', 'Nariko', 'Ioselevich', '07/06/1987');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('China Fund, Inc. (The)', 'Bremen', 'Shea', 'Bielby', '28/07/1987');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('CNX Coal Resources LP', 'Steanson', 'Saxon', 'Look', '20/03/1913');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Partner Communications Company Ltd.', 'Brimm', 'Pavlov', 'Vaar', '13/05/2013');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Plumas Bancorp', 'Fulk', 'Gamaliel', 'Sugars', '09/11/1964');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Regional Management Corp.', 'Basilio', 'Alexandra', 'Pozzo', '06/03/2016');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Patriot Transportation Holding, Inc.', 'Pear', 'Ianthe', 'De Benedetti', '12/06/1918');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('AngioDynamics, Inc.', 'Hadgraft', 'Pippo', 'Easey', '20/11/1932');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('trivago N.V.', 'Florio', 'Mollie', 'Lowman', '19/01/1921');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('WisdomTree Emerging Markets Corporate Bond Fund', 'MacElane', 'Raina', 'Casini', '14/07/1955');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Boulevard Acquisition Corp. II', 'Labbez', 'Cully', 'Gorriessen', '27/06/1947');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Michael Kors Holdings Limited', 'Ridout', 'Linn', 'Yuille', '03/08/2012');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Donaldson Company, Inc.', 'Deboo', 'Kristel', 'Lang', '21/01/1904');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('China Southern Airlines Company Limited', 'Connell', 'Farlay', 'Cornick', '09/06/1947');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('STERIS plc', 'Walak', 'Jessica', 'Hurdidge', '22/08/2016');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Zymeworks Inc.', 'Coping', 'Wendi', 'Luckin', '02/02/1954');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Altria Group', 'Bostock', 'Dal', 'Masser', '04/09/1993');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Horizons DAX Germany ETF', 'De Ambrosi', 'Minna', 'Ambrozik', '02/08/2016');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Carbo Ceramics, Inc.', 'Radki', 'Padriac', 'Sanham', '02/06/1959');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Stericycle, Inc.', 'Pleace', 'Nita', 'Bourdon', '10/12/1924');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Auburn National Bancorporation, Inc.', 'Lowdyane', 'Stefan', 'Peizer', '23/10/1924');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Southern Company (The)', 'Dickson', 'Heloise', 'Cahillane', '02/03/1966');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Cellcom Israel, Ltd.', 'MacGaughey', 'Nixie', 'Monger', '08/07/1982');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Tilly''s, Inc.', 'Frear', 'Kathlin', 'Jayume', '28/03/2018');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Monster Beverage Corporation', 'Saket', 'Nat', 'Riolfo', '06/10/2002');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Onconova Therapeutics, Inc.', 'Chiddy', 'Freida', 'Coots', '26/12/1975');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Kennedy-Wilson Holdings Inc.', 'Cuxon', 'Adriaens', 'Rentoul', '19/04/2000');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Artesian Resources Corporation', 'Duchart', 'Rad', 'Camillo', '19/02/1917');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Advanced Disposal Services, Inc.', 'Deely', 'Henry', 'Canty', '30/06/2000');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('SAP SE', 'Goldbourn', 'Gretchen', 'Pady', '29/09/1914');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Regency Centers Corporation', 'Leband', 'Sax', 'Roderighi', '13/10/1981');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('CBRE Clarion Global Real Estate Income Fund', 'Berardt', 'Lorenza', 'Rookes', '20/01/1953');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Snap-On Incorporated', 'Jurasek', 'Merwyn', 'Dyke', '05/08/1981');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Gabelli Multi-Media Trust Inc. (The)', 'Morch', 'Sonnie', 'Bazoche', '17/07/1918');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Gener8 Maritime, Inc.', 'Southcomb', 'Pammy', 'Maly', '16/05/1928');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('East West Bancorp, Inc.', 'Percy', 'Robenia', 'Tender', '05/04/1942');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('MFC Bancorp Ltd.', 'De Santos', 'Kennith', 'Dee', '31/03/1904');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Vistra Energy Corp.', 'Airlie', 'Marlane', 'Spurdens', '14/06/1904');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Fulgent Genetics, Inc.', 'Falvey', 'Udell', 'Britto', '21/03/1927');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Avid Technology, Inc.', 'Girke', 'Selig', 'Truran', '15/04/1903');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Sphere 3D Corp.', 'Corbyn', 'Lefty', 'Cribbott', '21/11/1934');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Thomson Reuters Corp', 'McCaskill', 'Lacie', 'Mulmuray', '19/03/1943');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('UGI Corporation', 'Robjohns', 'Neville', 'Nurse', '11/05/1975');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Alphabet Inc.', 'Shotter', 'Rica', 'Huet', '24/09/1909');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Tiptree Inc.', 'Kemwal', 'Gwendolen', 'Bellison', '12/05/1992');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('J P Morgan Chase & Co', 'Savin', 'Afton', 'Brik', '04/10/1953');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Southside Bancshares, Inc.', 'Chetwind', 'Opal', 'Turneux', '31/12/1912');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('MS Structured Asset Corp Saturns GE Cap Corp Series 2002-14', 'Coyte', 'Pia', 'Blanpein', '21/05/2009');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('John Hancock Premium Dividend Fund', 'Kemery', 'Terza', 'Doggrell', '23/11/1969');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('MarineMax, Inc.', 'Crumpe', 'Arie', 'Radford', '12/06/1955');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('AeroVironment, Inc.', 'Pillman', 'Ilene', 'Duigenan', '17/01/1964');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Pfizer, Inc.', 'MacGillavery', 'Meredithe', 'Binnie', '11/06/1937');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Peapack-Gladstone Financial Corporation', 'Ingilson', 'Earl', 'Bigland', '06/05/1973');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Arbor Realty Trust', 'Brownsword', 'Deborah', 'Miskimmon', '10/07/1969');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('EchoStar Corporation', 'Audley', 'Timoteo', 'McRobert', '02/02/1997');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Western Asset Emerging Markets Debt Fund Inc', 'Rideout', 'Delores', 'Edelheid', '18/03/1913');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Dupont Fabros Technology, Inc.', 'Hawket', 'Ashli', 'Kibbye', '11/02/1961');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('O2Micro International Limited', 'Isaac', 'Monroe', 'Eagleston', '14/09/1958');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Wheeler Real Estate Investment Trust, Inc.', 'Arundell', 'Serge', 'Tryhorn', '28/03/1917');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Apogee Enterprises, Inc.', 'Ainley', 'Arluene', 'Tassell', '01/07/1922');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Amdocs Limited', 'Crome', 'Tobe', 'Snyder', '04/08/1949');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('First Trust NASDAQ Cybersecurity ETF', 'Tucsell', 'Herta', 'Jepson', '16/07/1906');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('DHT Holdings, Inc.', 'Brandenberg', 'Bonnibelle', 'Reeve', '29/10/1901');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('ICC Holdings, Inc.', 'Gyse', 'Ryley', 'Peiro', '08/05/1931');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Graco Inc.', 'Bloore', 'Rikki', 'Pechard', '13/12/1904');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Stepan Company', 'Danneil', 'Hershel', 'Brookesbie', '21/01/1987');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Lennar Corporation', 'Brobyn', 'Virgie', 'Flint', '28/08/1998');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Qualstar Corporation', 'Crinage', 'Deanne', 'Skoof', '08/04/2010');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Progressive Corporation (The)', 'McKitterick', 'Jillane', 'Sackey', '07/12/2003');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Tetra Technologies, Inc.', 'Layson', 'Gardener', 'Bispo', '27/02/1949');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Innospec Inc.', 'Harbison', 'Tommy', 'O''Rudden', '05/02/2020');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Empire State Realty Trust, Inc.', 'Boath', 'Perrine', 'Oaker', '15/02/1912');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Adient plc', 'Rodenhurst', 'Roanna', 'Burr', '17/01/2015');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('ProPhase Labs, Inc.', 'Yitzhok', 'Elyn', 'Ben', '13/03/2018');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('PowerShares S&P SmallCap Information Technology Portfolio', 'Hoggan', 'Alisun', 'Hrus', '29/11/1929');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('F.N.B. Corporation', 'Yu', 'Em', 'Habgood', '13/02/1979');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Lawson Products, Inc.', 'Poynton', 'Dasya', 'Cobello', '30/11/1967');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Vedanta  Limited', 'Buckles', 'Ethelda', 'Gofford', '13/03/1973');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('The Charles Schwab Corporation', 'Humbee', 'Callean', 'Medling', '16/01/1976');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Gabelli Equity Trust, Inc. (The)', 'Harrowell', 'Roth', 'Conti', '01/03/1947');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Daseke, Inc.', 'Insko', 'Clementius', 'Gillise', '01/08/1931');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Matlin & Partners Acquisition Corporation', 'Mucklestone', 'Priscilla', 'Kohnert', '13/01/1986');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Healthcare Services Group, Inc.', 'Grinsted', 'Talia', 'Lownie', '06/02/1969');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Southern California Edison Company', 'Espino', 'Brendin', 'O''Bradden', '19/07/1925');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('American Homes 4 Rent', 'Loges', 'Drugi', 'Lake', '02/10/1920');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Bank of America Corporation', 'Annakin', 'Dermot', 'Walcher', '20/08/1948');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('CorVel Corp.', 'Smalecombe', 'Ardelle', 'Atcherley', '25/01/2004');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('HFF, Inc.', 'Glanister', 'Osborne', 'Mottinelli', '08/09/2021');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Wells Fargo & Company', 'Lindstrom', 'Bail', 'Haxley', '10/12/1993');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Turtle Beach Corporation', 'Chaloner', 'Jermain', 'Muffett', '25/06/1932');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('InnerWorkings, Inc.', 'McCartan', 'Arabel', 'MacGorley', '27/02/2003');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Capitala Finance Corp.', 'Garratt', 'Luci', 'Fley', '23/03/1998');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Boyd Gaming Corporation', 'Damrell', 'Granny', 'Fernandes', '22/06/1962');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Euro Tech Holdings Company Limited', 'Checo', 'Claiborne', 'Polding', '02/10/2001');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('World Wrestling Entertainment, Inc.', 'Hanstock', 'Coop', 'Thandi', '19/04/1992');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('BLDRS Developed Markets 100 ADR Index Fund', 'Fowden', 'Dody', 'Carlisi', '21/09/1905');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Cara Therapeutics, Inc.', 'Victoria', 'Doroteya', 'Acomb', '08/10/1989');
insert into Company (company_name, last_name_owner, first_name_owner, middle_name_owner, date_of_creation) values ('Aurinia Pharmaceuticals Inc', 'Praundl', 'Reta', 'Rigmand', '07/11/1995');
