//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accountants_Tools.entity_framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Company_positions = new HashSet<Company_positions>();
        }
    
        public long id { get; set; }
        public string company_name { get; set; }
        public string last_name_owner { get; set; }
        public string first_name_owner { get; set; }
        public string middle_name_owner { get; set; }
        public System.DateTime date_of_creation { get; set; }
        public string company_description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_positions> Company_positions { get; set; }
    }
}
