//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accountants_Tools.entity_framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_positions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company_positions()
        {
            this.Employment_contracts = new HashSet<Employment_contracts>();
        }
    
        public long id { get; set; }
        public string name_position { get; set; }
        public int salary_for_position { get; set; }
        public string description_position { get; set; }
        public long id_company { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employment_contracts> Employment_contracts { get; set; }
    }
}
