//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accountants_Tools.entity_framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employment_contracts
    {
        public long id { get; set; }
        public System.DateTime date_of_conclusion { get; set; }
        public long id_employee { get; set; }
        public long id_position { get; set; }
    
        public virtual Company_positions Company_positions { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
